# New Car Sales Prediction


Company has newly lunched XUV in high price range so we will predict if the customer is going to buy new car or not based on social network data

This dataset contain information of user and social network, those features are - userid,gender,age,salary,purchased

Last column tell us user purchased the car yes-1 // no-0 & we are going to build the model that is going to predict if the user is going to buy xuv or not based on 2 variable based on age & estimated salary
so our matrix of feature is only these 2 column & we gonna find some corelation b/w age and estimated salary of user and his decission to purchase the car [yes or no]
so we need 2 index and rest of index i will remove for this i have to use slicing operator
1 means - the user going to buy the car & 0 means - user is not going to buy the car

In [1]:
#importing Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
#import dataset
dataset=pd.read_csv(r'C:\Users\Lenovo\Desktop\Arun DS\May\May 3rd Logistic Reg\2.LOGISTIC REGRESSION CODE\Social_Network_Ads.CSV.csv')

In [3]:
dataset.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
X=dataset.iloc[:,3:4].values
y=dataset.iloc[:,-1].values

In [10]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

We have taken 25% for the test set

In [12]:
#Feature scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

C:\Users\Lenovo\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\Lenovo\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


we have done feature scaling only to independent variable not dependent variable.

Next step is we are going to build the logistic model and apply this model into our dataset

In [50]:
#Logistic Regression
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()
classifier.fit(X_train,y_train)

#predicting the test set results
y_pred=classifier.predict(X_test)

C:\Users\Lenovo\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [51]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1], dtype=int64)

if u look at the first observation this user is not be able to buy the car but if you look at observation 7 then that user is going to buy the car
in this case logistic regression model classify which users are going to buy the car or not 

we build our logistic model and fit it to the training set & we predict our test set result 
now we will use the confusion matrix to evalute

In [52]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(y_pred,y_test))


print('Accuracy:', accuracy_score(y_pred,y_test))

print(classification_report(y_pred,y_test))

[[66 17]
 [ 2 15]]
Accuracy: 0.81
              precision    recall  f1-score   support

           0       0.97      0.80      0.87        83
           1       0.47      0.88      0.61        17

   micro avg       0.81      0.81      0.81       100
   macro avg       0.72      0.84      0.74       100
weighted avg       0.89      0.81      0.83       100



Lets add few more algorithms and check the accuracy

KNN : 

In [53]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier()
classifier.fit(X_train,y_train)

y_pred=classifier.predict(X_test)

In [54]:
print(confusion_matrix(y_test,y_pred))
print('Accuracy: ',accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[60  8]
 [10 22]]
Accuracy:  0.82
              precision    recall  f1-score   support

           0       0.86      0.88      0.87        68
           1       0.73      0.69      0.71        32

   micro avg       0.82      0.82      0.82       100
   macro avg       0.80      0.78      0.79       100
weighted avg       0.82      0.82      0.82       100



SVM:

In [66]:
from sklearn.svm import SVC
classifier=SVC()
classifier.fit(X_train,y_train)

y_pred=classifier.predict(X_test)

In [67]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(y_test,y_pred))
print('Accuracy: ',accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[66  2]
 [17 15]]
Accuracy:  0.81
              precision    recall  f1-score   support

           0       0.80      0.97      0.87        68
           1       0.88      0.47      0.61        32

   micro avg       0.81      0.81      0.81       100
   macro avg       0.84      0.72      0.74       100
weighted avg       0.82      0.81      0.79       100

